name: S4TF
favicon: null
layout_spectrum: 0.20744099863804877
typography_spectrum: 0.5368145434185863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121315'
    - '#a7a7a7'
    - '#6a6a6a'
    - '#ffffff'
    - '#78d3db'
  brandStrength: 0.4375
  lightness: 0.6119579419028014
  saturation: 0.6754664115142077
  rhythmicContrast: 0.7387541544158012
purpose: []
