typography_spectrum: 0.54898
color:
  brandColors:
    - '#ffffff'
    - '#cbcbcb'
    - '#ececec'
    - '#e0e0e0'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20744099863804877
analytics:
  google: null
  facebook: null
  twitter: null
name: S4TF
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Somethin' 4 The Fellas
description: Overindulged
purpose: []
