name: S4TF
favicon: null
layout_spectrum: 0.20744099863804877
typography_spectrum: 0.5368145434185863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30216846731491387
  lightness: 0.6119579419028014
  saturation: 0.6754664115142077
  rhythmicContrast: 0.7387541544158012
purpose: []
