name: S4TF
favicon: null
layout_spectrum: 0.20744099863804877
typography_spectrum: 0.5368145434185863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfd'
    - '#000000'
    - '#636363'
    - '#a7b4b7'
    - '#69fd8d'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
